name: 'TRM Publish'
description: 'Publish a package to TRM Registry'
author: 'Simone Gaffurini'
branding:
  icon: 'upload'
  color: 'yellow'
inputs:
  systemDest:
    description: Origin system ID
    required: true
  systemAsHost:
    description: Origin system application Server
    required: true
  systemSysnr:
    description: Origin system instance number
    required: true
  systemSapRouter:
    description: Origin system SAProuter
    required: false
  systemClient:
    description: Origin system logon client
    required: true
  systemUser:
    description: Origin system logon user
    required: true
  systemPassword:
    description: Origin system logon password
    required: true
  systemLang:
    description: Origin system logon language
    required: true
  devclass:
    description: SAP Package
    required: true
  target:
    description: SAP Transport release target
    required: true
  registryEndpoint:
    description: Registry endpoint
    default: public
    required: false
  registryAuth:
    description: Registry authentication in JSON format
    required: false
  packageName:
    description: Package name (on registry)
    required: true
  packageVersion:
    description: Package version (on registry)
    default: latest
    required: false
  description:
    description: Package short description
    required: false
  private:
    description: Package visibility
    default: false
    required: false
  git:
    description: Git repository url
    required: false
  website:
    description: Package website url
    required: false
  license:
    description: Package SPDX license
    required: false
  authors:
    description: Package authors separated by comma
    required: false
  keywords:
    description: Package keywords separated by comma
    required: false
  readme:
    description: Package readme or path to readme file
    required: false
  releaseTimeout:
    description: Transport request release timeout, in seconds (increase for larger packages)
    default: 180
    required: false
  overwriteManifestValues:
    description: Overwrite existing manifest values from previous release from registry
    default: true
    required: false
  skipDependencies:
    description: Skip seraching for TRM/SAP Entries dependencies
    default: false
    required: false
  skipLang:
    description: Skip translation transport generation
    default: false
    required: false
  backwardsCompatible:
    description: Indicates that the current release is backwards compatible with the previous releases
    default: true
    required: false
  custTransports:
    description: Customizing transports separated by comma to include (main transports are sufficient)
    required: false
  dependencies:
    description: Manually added TRM dependencies in JSON format
    required: false
  sapEntries:
    description: Manually added SAP Entries in JSON format
    required: false
  tmpFolder:
    description: Directory for temporary files
    required: false
  simpleLog:
    description: Don't use Github Actions annotations on important log messages
    default: false
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'